---
- name: "Download filebeat"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    mode: 0755
  register: filebeat_download
  until: filebeat_download is succeeded
- name: "Install filebeat"
  become: true
  yum:
    name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    state: present
- name: "Configure filebeat"
  become: true
  template:
    src: "templates/filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    mode: 0755
  notify: restart filebeat
